[package]
name = "Uniswap-V3"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy-primitives = "1.2.1"
anyhow = "1.0.98"
serde_json = "1.0.141"
thiserror = "2.0.12"
alloy = { version = "1.0.3", features = [
    "contract",
    "providers",
], optional = true }
